apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-1lex
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0052-tenant/tkrw-pr712-0075-0052-app/devfile-sample-1lex@sha256:78dc1c808cdce9a1afc6ae699871bf4448ae8a230d47477832e54a85bd761df1
        name: my-nodejs
        resources: {}
status: {}
